


######################################################################
[INIT : 0_complete_graph_with_9_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 1}
2 {'color': 2}
3 {'color': 1}
4 {'color': 2}
5 {'color': 0}
6 {'color': 1}
7 {'color': 2}
8 {'color': 1}

[number of nodes] = 9


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 7, 1: 3, 2: 10}
1 {0: 7, 1: 2, 2: 6}
2 {0: 4, 1: 8, 2: 4}
3 {0: 3, 1: 8, 2: 8}
4 {0: 6, 1: 7, 2: 10}
5 {0: 4, 1: 5, 2: 3}
6 {0: 7, 1: 1, 2: 5}
7 {0: 9, 1: 3, 2: 2}
8 {0: 2, 1: 9, 2: 9}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 8}
0 2 {'weight': 7}
0 3 {'weight': 3}
0 4 {'weight': 8}
0 5 {'weight': 3}
0 6 {'weight': 6}
0 7 {'weight': 3}
0 8 {'weight': 1}
1 2 {'weight': 10}
1 3 {'weight': 3}
1 4 {'weight': 10}
1 5 {'weight': 3}
1 6 {'weight': 6}
1 7 {'weight': 5}
1 8 {'weight': 1}
2 3 {'weight': 9}
2 4 {'weight': 5}
2 5 {'weight': 5}
2 6 {'weight': 1}
2 7 {'weight': 1}
2 8 {'weight': 7}
3 4 {'weight': 3}
3 5 {'weight': 5}
3 6 {'weight': 6}
3 7 {'weight': 9}
3 8 {'weight': 8}
4 5 {'weight': 4}
4 6 {'weight': 8}
4 7 {'weight': 2}
4 8 {'weight': 7}
5 6 {'weight': 6}
5 7 {'weight': 6}
5 8 {'weight': 10}
6 7 {'weight': 9}
6 8 {'weight': 8}
7 8 {'weight': 9}

[number of edges] = 36


######################################################################
[INIT : 1_complete_graph_with_9_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 1}
2 {'color': 2}
3 {'color': 1}
4 {'color': 1}
5 {'color': 1}
6 {'color': 0}
7 {'color': 2}
8 {'color': 0}

[number of nodes] = 9


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 6, 1: 10, 2: 7}
1 {0: 7, 1: 7, 2: 7}
2 {0: 8, 1: 1, 2: 4}
3 {0: 6, 1: 7, 2: 9}
4 {0: 1, 1: 1, 2: 3}
5 {0: 8, 1: 10, 2: 6}
6 {0: 8, 1: 2, 2: 5}
7 {0: 9, 1: 5, 2: 4}
8 {0: 2, 1: 2, 2: 0}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 2}
0 2 {'weight': 9}
0 3 {'weight': 4}
0 4 {'weight': 4}
0 5 {'weight': 10}
0 6 {'weight': 9}
0 7 {'weight': 5}
0 8 {'weight': 9}
1 2 {'weight': 7}
1 3 {'weight': 3}
1 4 {'weight': 8}
1 5 {'weight': 1}
1 6 {'weight': 3}
1 7 {'weight': 8}
1 8 {'weight': 3}
2 3 {'weight': 8}
2 4 {'weight': 10}
2 5 {'weight': 5}
2 6 {'weight': 4}
2 7 {'weight': 5}
2 8 {'weight': 8}
3 4 {'weight': 7}
3 5 {'weight': 2}
3 6 {'weight': 9}
3 7 {'weight': 6}
3 8 {'weight': 7}
4 5 {'weight': 5}
4 6 {'weight': 10}
4 7 {'weight': 3}
4 8 {'weight': 4}
5 6 {'weight': 9}
5 7 {'weight': 5}
5 8 {'weight': 7}
6 7 {'weight': 4}
6 8 {'weight': 5}
7 8 {'weight': 2}

[number of edges] = 36


######################################################################
[INIT : 2_complete_graph_with_6_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 2}
2 {'color': 1}
3 {'color': 2}
4 {'color': 2}
5 {'color': 1}

[number of nodes] = 6


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 3, 1: 9, 2: 8}
1 {0: 1, 1: 3, 2: 8}
2 {0: 5, 1: 0, 2: 1}
3 {0: 2, 1: 6, 2: 1}
4 {0: 2, 1: 2, 2: 10}
5 {0: 1, 1: 2, 2: 4}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 9}
0 2 {'weight': 3}
0 3 {'weight': 6}
0 4 {'weight': 9}
0 5 {'weight': 8}
1 2 {'weight': 6}
1 3 {'weight': 7}
1 4 {'weight': 6}
1 5 {'weight': 7}
2 3 {'weight': 10}
2 4 {'weight': 3}
2 5 {'weight': 1}
3 4 {'weight': 9}
3 5 {'weight': 2}
4 5 {'weight': 8}

[number of edges] = 15


######################################################################
[INIT : 3_complete_graph_with_8_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 2}
1 {'color': 2}
2 {'color': 2}
3 {'color': 1}
4 {'color': 1}
5 {'color': 2}
6 {'color': 2}
7 {'color': 1}

[number of nodes] = 8


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 2, 1: 2, 2: 1}
1 {0: 9, 1: 5, 2: 6}
2 {0: 5, 1: 5, 2: 2}
3 {0: 5, 1: 5, 2: 9}
4 {0: 7, 1: 1, 2: 3}
5 {0: 6, 1: 4, 2: 6}
6 {0: 5, 1: 10, 2: 10}
7 {0: 1, 1: 3, 2: 4}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 9}
0 2 {'weight': 2}
0 3 {'weight': 10}
0 4 {'weight': 4}
0 5 {'weight': 8}
0 6 {'weight': 8}
0 7 {'weight': 9}
1 2 {'weight': 3}
1 3 {'weight': 5}
1 4 {'weight': 4}
1 5 {'weight': 4}
1 6 {'weight': 7}
1 7 {'weight': 2}
2 3 {'weight': 8}
2 4 {'weight': 1}
2 5 {'weight': 1}
2 6 {'weight': 7}
2 7 {'weight': 5}
3 4 {'weight': 7}
3 5 {'weight': 8}
3 6 {'weight': 6}
3 7 {'weight': 5}
4 5 {'weight': 2}
4 6 {'weight': 6}
4 7 {'weight': 4}
5 6 {'weight': 5}
5 7 {'weight': 5}
6 7 {'weight': 6}

[number of edges] = 28


######################################################################
[INIT : 4_complete_graph_with_5_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 1}
2 {'color': 2}
3 {'color': 2}
4 {'color': 2}

[number of nodes] = 5


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 5, 1: 3, 2: 10}
1 {0: 9, 1: 1, 2: 10}
2 {0: 9, 1: 9, 2: 3}
3 {0: 8, 1: 7, 2: 2}
4 {0: 4, 1: 0, 2: 2}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 2}
0 2 {'weight': 5}
0 3 {'weight': 4}
0 4 {'weight': 10}
1 2 {'weight': 2}
1 3 {'weight': 4}
1 4 {'weight': 1}
2 3 {'weight': 2}
2 4 {'weight': 10}
3 4 {'weight': 9}

[number of edges] = 10


######################################################################
[INIT : 5_complete_graph_with_9_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 2}
1 {'color': 2}
2 {'color': 1}
3 {'color': 0}
4 {'color': 0}
5 {'color': 2}
6 {'color': 2}
7 {'color': 2}
8 {'color': 0}

[number of nodes] = 9


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 10, 1: 5, 2: 0}
1 {0: 3, 1: 7, 2: 10}
2 {0: 5, 1: 4, 2: 5}
3 {0: 8, 1: 8, 2: 2}
4 {0: 7, 1: 8, 2: 0}
5 {0: 9, 1: 6, 2: 8}
6 {0: 10, 1: 6, 2: 5}
7 {0: 7, 1: 7, 2: 7}
8 {0: 9, 1: 3, 2: 3}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 7}
0 2 {'weight': 5}
0 3 {'weight': 5}
0 4 {'weight': 2}
0 5 {'weight': 6}
0 6 {'weight': 7}
0 7 {'weight': 7}
0 8 {'weight': 10}
1 2 {'weight': 5}
1 3 {'weight': 1}
1 4 {'weight': 1}
1 5 {'weight': 8}
1 6 {'weight': 8}
1 7 {'weight': 8}
1 8 {'weight': 8}
2 3 {'weight': 6}
2 4 {'weight': 7}
2 5 {'weight': 8}
2 6 {'weight': 4}
2 7 {'weight': 1}
2 8 {'weight': 8}
3 4 {'weight': 4}
3 5 {'weight': 10}
3 6 {'weight': 5}
3 7 {'weight': 5}
3 8 {'weight': 2}
4 5 {'weight': 1}
4 6 {'weight': 3}
4 7 {'weight': 7}
4 8 {'weight': 4}
5 6 {'weight': 1}
5 7 {'weight': 1}
5 8 {'weight': 8}
6 7 {'weight': 6}
6 8 {'weight': 4}
7 8 {'weight': 5}

[number of edges] = 36


######################################################################
[INIT : 6_complete_graph_with_3_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 1}
1 {'color': 1}
2 {'color': 2}

[number of nodes] = 3


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 0, 1: 8, 2: 6}
1 {0: 2, 1: 8, 2: 2}
2 {0: 2, 1: 1, 2: 3}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 2}
0 2 {'weight': 6}
1 2 {'weight': 5}

[number of edges] = 3


######################################################################
[INIT : 7_complete_graph_with_7_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 0}
2 {'color': 0}
3 {'color': 0}
4 {'color': 0}
5 {'color': 0}
6 {'color': 2}

[number of nodes] = 7


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 0, 1: 0, 2: 1}
1 {0: 2, 1: 6, 2: 5}
2 {0: 7, 1: 4, 2: 9}
3 {0: 5, 1: 8, 2: 3}
4 {0: 9, 1: 10, 2: 2}
5 {0: 5, 1: 9, 2: 8}
6 {0: 9, 1: 2, 2: 5}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 9}
0 2 {'weight': 5}
0 3 {'weight': 8}
0 4 {'weight': 3}
0 5 {'weight': 7}
0 6 {'weight': 6}
1 2 {'weight': 3}
1 3 {'weight': 5}
1 4 {'weight': 5}
1 5 {'weight': 5}
1 6 {'weight': 4}
2 3 {'weight': 10}
2 4 {'weight': 5}
2 5 {'weight': 9}
2 6 {'weight': 7}
3 4 {'weight': 9}
3 5 {'weight': 10}
3 6 {'weight': 5}
4 5 {'weight': 5}
4 6 {'weight': 2}
5 6 {'weight': 8}

[number of edges] = 21


######################################################################
[INIT : 8_complete_graph_with_5_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 2}
1 {'color': 0}
2 {'color': 1}
3 {'color': 2}
4 {'color': 2}

[number of nodes] = 5


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 9, 1: 6, 2: 3}
1 {0: 8, 1: 2, 2: 2}
2 {0: 4, 1: 1, 2: 8}
3 {0: 2, 1: 3, 2: 2}
4 {0: 5, 1: 9, 2: 9}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 9}
0 2 {'weight': 7}
0 3 {'weight': 5}
0 4 {'weight': 8}
1 2 {'weight': 5}
1 3 {'weight': 7}
1 4 {'weight': 4}
2 3 {'weight': 4}
2 4 {'weight': 10}
3 4 {'weight': 5}

[number of edges] = 10


######################################################################
[INIT : 9_complete_graph_with_8_nodes.edgelist ]


COLORS (LIST) [STATIC MODE]

[0, 1, 2]

3


NODE -- COLOR (LIST OF DICTIONARY) == INITIAL COLOURING

0 {'color': 0}
1 {'color': 0}
2 {'color': 0}
3 {'color': 2}
4 {'color': 2}
5 {'color': 0}
6 {'color': 0}
7 {'color': 2}

[number of nodes] = 8


NODE -- COLORS -- PROFITS (NESTED DICTIONARY)

0 {0: 3, 1: 3, 2: 4}
1 {0: 4, 1: 0, 2: 9}
2 {0: 9, 1: 1, 2: 10}
3 {0: 1, 1: 0, 2: 5}
4 {0: 4, 1: 9, 2: 7}
5 {0: 0, 1: 4, 2: 1}
6 {0: 6, 1: 7, 2: 8}
7 {0: 6, 1: 3, 2: 3}



NODE -- NODE -- EDGE WEIGHT (LIST OF LIST OF DICTIONARY)

0 1 {'weight': 10}
0 2 {'weight': 5}
0 3 {'weight': 10}
0 4 {'weight': 4}
0 5 {'weight': 6}
0 6 {'weight': 10}
0 7 {'weight': 4}
1 2 {'weight': 5}
1 3 {'weight': 3}
1 4 {'weight': 2}
1 5 {'weight': 9}
1 6 {'weight': 3}
1 7 {'weight': 6}
2 3 {'weight': 10}
2 4 {'weight': 7}
2 5 {'weight': 4}
2 6 {'weight': 1}
2 7 {'weight': 3}
3 4 {'weight': 6}
3 5 {'weight': 1}
3 6 {'weight': 3}
3 7 {'weight': 1}
4 5 {'weight': 4}
4 6 {'weight': 5}
4 7 {'weight': 7}
5 6 {'weight': 4}
5 7 {'weight': 2}
6 7 {'weight': 2}

[number of edges] = 28